# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# General configuration
[character]
success_symbol = "âœ"
error_symbol = "âœ—"

# Git configuration
[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
conflicted = "ğŸ³ï¸ "
ahead = "ğŸï¸ ğŸ’¨ "
behind = "ğŸ¢ "
diverged = "ğŸ”€ "
untracked = "ğŸ“ "
stashed = "ğŸ“¦ "
modified = "âœï¸ "
staged = "ğŸ—ƒï¸ "
renamed = "ğŸ“› "
deleted = "ğŸ—‘ï¸ "

# Docker configuration
[docker_context]
symbol = "ğŸ³ "
style = "bold blue"

# Kubernetes configuration
[kubernetes]
symbol = "â˜¸ï¸ "
style = "bold blue"

# Terraform configuration
[terraform]
symbol = "ğŸ”§ "
detect_files = ["provider.tf", "main.tf", ".terraform"]
style = "bold 105"

# Node.js configuration
[nodejs]
symbol = "â¬¢ "
style = "bold green"

# Python configuration
[python]
symbol = "ğŸ "
style = "bold yellow"

# Rust configuration
[rust]
symbol = "ğŸ¦€ "
style = "bold red"

# Go configuration
[golang]
symbol = "ğŸ¹ "
style = "bold cyan"

# Shell configuration
#[shell]
#symbol = "ğŸš "
#style = "bold magenta"

# AWS configuration
[aws]
symbol = "â˜ï¸  "
style = "bold yellow"

# Azure configuration
[azure]
symbol = "â˜ï¸  "
style = "bold blue"

# GCP configuration
[gcloud]
symbol = "â˜ï¸  "
style = "bold red"

# Helm configuration
[helm]
symbol = "âˆ "
style = "bold blue"

# Custom section for showing the current directory
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
disabled = false

# Time configuration
[time]
format = "ğŸ•’ %T"
disabled = false
